use projeto;
select * from tb_personagem;
select * from tb_usuario;
select * from tb_participante;
select * from tb_campanha;
select * from tb_regras;
select * from tb_personagem;
select * from tb_pericias;
select * from tb_rolagem;
select * from tb_proficiencia;
select * from tb_outraproficiencia;
select * from tb_atributos;
select * from tb_talentotraco;
select * from tb_moedas;
select * from tb_equipamento;
select * from tb_magia;
select * from tb_ataquesconjuracao;